package com.example.terrirun

fun appText(key: String, language: String): String {
    return when (language) {
        "en" -> when (key) {
            "map" -> "Map"
            "ranking" -> "Ranking"
            "profile" -> "Profile"
            "settings" -> "Settings"
            "language" -> "Language"
            "notifications" -> "Notifications"
            "privacy" -> "Privacy"
            "back" -> "Back"
            "logout" -> "Log out"
            "activate_notifications" -> "Enable notifications"
            "activate_notifications_text" -> "Do you want to enable notifications to receive alerts when your territories are attacked?"
            "yes" -> "Yes"
            "no" -> "No"
            "activity" -> "Activity"
            "time" -> "Time"
            "distance" -> "Distance"
            "capital_reinforcement" -> "Capital reinforcement"
            "start_activity" -> "Start activity"
            "stop_activity" -> "Stop activity"
            "my_territories" -> "My territories"
            "profile_progress" -> "Kingdom progress"
            "territories" -> "Territories"
            "villages" -> "Villages"
            "control" -> "Control"
            "ranking_title" -> "Kingdom ranking"
            "ranking_subtitle" -> "Ranking by total control and conquered territories"
            "general_ranking" -> "General ranking"
            "tap_details" -> "Tap to view details"
            "show_territories" -> "Tap to view territories"
            "hide_territories" -> "Hide territories"
            "go_capital" -> "Go to capital"
            "calories" -> "Calories"
            "notifications" -> "Notifications"
            else -> key
        }

        else -> when (key) {
            "map" -> "Mapa"
            "ranking" -> "Ranking"
            "profile" -> "Perfil"
            "settings" -> "Ajustes"
            "language" -> "Idioma"
            "notifications" -> "Notificaciones"
            "privacy" -> "Privacidad"
            "back" -> "Volver"
            "logout" -> "Cerrar sesión"
            "activate_notifications" -> "Activar notificaciones"
            "activate_notifications_text" -> "¿Deseas activar las notificaciones para recibir avisos cuando ataquen tus territorios?"
            "yes" -> "Sí"
            "no" -> "No"
            "activity" -> "Actividad"
            "time" -> "Tiempo"
            "distance" -> "Distancia"
            "capital_reinforcement" -> "Refuerzo capital"
            "start_activity" -> "Iniciar actividad"
            "stop_activity" -> "Detener actividad"
            "my_territories" -> "Mis territorios"
            "profile_progress" -> "Progreso del reino"
            "territories" -> "Territorios"
            "villages" -> "Poblados"
            "control" -> "Control"
            "ranking_title" -> "Ranking de reinos"
            "ranking_subtitle" -> "Clasificación por control total y territorios conquistados"
            "general_ranking" -> "Clasificación general"
            "tap_details" -> "Pulsa para ver detalles"
            "show_territories" -> "Pulsa para ver territorios"
            "hide_territories" -> "Ocultar territorios"
            "go_capital" -> "Ir a la capital"
            "calories" -> "Calorías"
            "notifications" -> "Notificaciones"

            else -> key
        }
    }
}